import 'package:sociord/screens/explore/immersive_mode_screen.dart';
import 'package:sociord/utils/asset_path_constants.dart';

class ImmersiveMockData {
  static List<ImmersivePost> getImmersivePosts() {
    return [
      ImmersivePost(
        id: '1',
        imageUrl: kExploreQuickies1,
        username: 'thatkindofgirl',
        title: 'Looking after a newborn',
        likes: 20000,
        comments: 500000,
        views: 250000,
        timeAgo: '10 days ago',
      ),
      ImmersivePost(
        id: '2',
        imageUrl: kExploreQuickies2,
        username: 'creative_soul',
        title: 'Morning coffee vibes',
        likes: 15000,
        comments: 320000,
        views: 180000,
        timeAgo: '2 days ago',
      ),
      ImmersivePost(
        id: '3',
        imageUrl: kExploreQuickies3,
        username: 'art_lover',
        title: 'Sunset painting session',
        likes: 25000,
        comments: 450000,
        views: 300000,
        timeAgo: '5 days ago',
      ),
      ImmersivePost(
        id: '4',
        imageUrl: kExploreQuickies4,
        username: 'design_guru',
        title: 'Minimalist workspace setup',
        likes: 18000,
        comments: 280000,
        views: 220000,
        timeAgo: '1 week ago',
      ),
      ImmersivePost(
        id: '5',
        imageUrl: kExploreQuickies5,
        username: 'photo_pro',
        title: 'Street photography tips',
        likes: 22000,
        comments: 380000,
        views: 280000,
        timeAgo: '3 days ago',
      ),
      ImmersivePost(
        id: '6',
        imageUrl: kExploreQuickies6,
        username: 'fashion_ista',
        title: 'Summer outfit ideas',
        likes: 30000,
        comments: 520000,
        views: 350000,
        timeAgo: '1 day ago',
      ),
      ImmersivePost(
        id: '7',
        imageUrl: kExploreQuickies7,
        username: 'food_blogger',
        title: 'Healthy breakfast bowl',
        likes: 12000,
        comments: 150000,
        views: 120000,
        timeAgo: '4 days ago',
      ),
      ImmersivePost(
        id: '8',
        imageUrl: kExploreQuickies8,
        username: 'travel_diary',
        title: 'Hidden gems in the city',
        likes: 35000,
        comments: 600000,
        views: 400000,
        timeAgo: '6 days ago',
      ),
      ImmersivePost(
        id: '9',
        imageUrl: kExploreQuickies9,
        username: 'music_producer',
        title: 'Behind the scenes studio',
        likes: 28000,
        comments: 420000,
        views: 320000,
        timeAgo: '2 days ago',
      ),
      ImmersivePost(
        id: '10',
        imageUrl: kExploreQuickies10,
        username: 'fitness_coach',
        title: 'Quick workout routine',
        likes: 20000,
        comments: 300000,
        views: 250000,
        timeAgo: '1 week ago',
      ),
    ];
  }
}
